<?php
$customerChatboxHelperData = $this->helper('THP\Chat\Helper\Data');
?>
<!-- Facebook Messenger -->
<?php if ($customerChatboxHelperData->getFacebookMessengerStatus()): ?>
<script>
    (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/<?= $block->getLocate(); ?>/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
<?= $customerChatboxHelperData->getFacebookMessengerChatCode(); ?>
<?php endif; ?>
<!-- End Facebook Messenger -->